devografiecms_homepage:
    path:     /hello/{name}
    defaults: { _controller: DevografiecmsBundle:Default:index }

indexadmin:
    path:     /devo_admin
    defaults: { _controller: DevografiecmsBundle:Administration:indexadmin }

editparametres:
    path:     /devo_admin/editparametres/{id}
    defaults: { _controller: DevografiecmsBundle:Administration:editparametres }
